spring.application.name=AuthService

server.port=8080


# --- DATABASE CONFIG (ENV-AWARE) ---
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#for dockerizing process we make this changes you can delete above lines and remove hash from below lines
# and u can run this project othherwise u can follow below steps 
# Right-click project -> Run As -> Run Configurations
# 2 Select your Spring Boot App
# 3 Go to Environment tab
# 4 Click New and add these:
# Name        	Value
# DB_URL	       jdbc:mysql://localhost:3306/authservicedb
# DB_USERNAME	root
# DB_PASSWORD	admin


# --- DATABASE CONFIG (ENV-AWARE) ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/authservicedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# --- JWT ---
jwt.secret=${JWT_SECRET:ReplaceWithASecureLongRandomStringAtLeast32CharsLong}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

